modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="frog_mod"
version="1.0.0"
displayName="Frog Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pifase, MCreator"
description='''
Adds frogs to Minecraft
'''

[[dependencies.frog_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




